config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users
  resources :events
  resources :attendances

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, foreign_key: "attendee_id", class_name: "User"
  belongs_to :attended_event, foreign_key: "attended_event_id", class_name: "Event"

  validates_uniqueness_of :attendee, :scope => :attended_event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: "creator_id", class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, :through => :attendances, source: :attendee

  scope :past, -> { where("date < ?", Date.today) }
  scope :future, -> { where("date > ?", Date.today) }

  validates :title, :location, :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, :through => :attendances, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    # @attendance = Attendance.new
  end

  def create

    @event = Event.find(params[:event_id])

    attendance = Attendance.new(attended_event_id: @event.id, attendee_id: current_user.id)

    if attendance.save
      flash[:notice] = "Your attendance has been noted!"
      redirect_to @event
    else
      flash[:error] = "You are already attending this event."
      redirect_to @event
    end
  end

  def destroy
    @event = Event.find(params[:id])
    puts "EVENT:", @event

    @attendance = Attendance.find_by(attended_event: params[:id], attendee_id: current_user.id)
    @attendance.destroy

    redirect_to @event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  
  def index
    @events = Event.all
  end

  def show

    @event = Event.find(params[:id])
    @attendance = Attendance.new
    @attendees = Attendance.where(attended_event: params[:id])
  end

  # GET /posts/new
  def new
    @event = Event.new
  end

  # POST /posts
  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:success] = "Event Successfully Saved!"
      redirect_to @event
    else
      flash.now[:error] = "Unable to create event!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:success] = "Event successfully edited!"
      redirect_to @event
    else
      flash.now[:error] = "Unable to edit event!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :body, :date, :location)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @events = Event.where(creator_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<h2>For user: <%= current_user.email if user_signed_in?%></h2>

<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>Enjoy these events!</h1>

<% @events.each do |event| %>
  <hr>
  <h2><%= link_to event.title, event_path(event.id) %></h2>
  <%= event.body %>
  <h4>This event will be held on <%= event.date %> in <%= event.location %></h4>
  <% if user_signed_in? %>
    <h5>Organized by <%= link_to event.creator.email, user_path(event.creator.id) %></h5>
  <% end %>
  <hr>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<hr>
<h1><%= @event.title %></h1>
<%= @event.body %>
<h4>This event will be held on <%= @event.date %> in <%= @event.location %></h4>
<% if user_signed_in? %>
  <h5>Organized by <%= link_to @event.creator.email, user_path(@event.creator.id) %></h5>
<% end %>
<% if user_signed_in? %>
  <%= button_to "Attend Event", attendances_path({event_id: @event.id}) %><br>
<% end %>  

<hr>
<h2>Confirmed Attendees</h2>
<ul>
<% @attendees.each do |attendee| %>
  <li>
    <%= link_to User.find(attendee.attendee_id).email, user_path(User.find(attendee.attendee_id))  %>
  </li>
  <% if user_signed_in? && attendee.attendee_id == current_user.id %>
    <%= button_to "Remove", attendance_path, method: :delete %>
  <% end %>
<% end %>
</ul>
<hr>

<% if current_user == @event.creator %>
  <%= button_to "Edit Event", edit_event_path, method: :get %><br>
  <%= button_to "DESTROY EVENT", @event, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <style>
    .success {
      background-color: green;
      font-size: 30px;
      }

    .error {
    background-color: red;
    font-size: 30px;
    }

    h1 {
      color: blue;

      }
  </style>

  <body>
    <%= link_to "HOME", root_path %><br>
    <%= link_to "PROFILE", user_path(current_user.id) if user_signed_in? %><br>
    <%= link_to "Sign Up", new_user_registration_path unless user_signed_in? %><br>
    <%= link_to "Sign In", new_user_session_path unless user_signed_in? %><br>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete if user_signed_in? %><br>
    <%= link_to "New Event", new_event_path if user_signed_in? %>
    
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<hr>
<h1>Profile page for <%= @user.email %><h1>
<h2>Events organized by <%= @user.email %></h2>
<ul>
  <% @events.each do |event| %>
    <li><h4><%= link_to event.title, event_path(event.id) %></h4></li>
  <% end %>
</ul>

<hr>
<h2>Events attended by <%= @user.email %></h2>
<ul>
  <h3>Future Events</h3>
    <% @user.attended_events.future.each do |attended_event| %>
      <li>
        <h4><%= link_to attended_event.title, event_path(attended_event) %></h4>
        <%= attended_event.date %>
      </li>
    <% end %>
  <hr>
  <h3>Past Events</h3>
    <% @user.attended_events.past.each do |attended_event| %>
      <li>
        <h4><%= link_to attended_event.title, event_path(attended_event) %></h4>
        <%= attended_event.date %>
      </li>
    <% end %>
</ul>